### ISSUE TITLE
[IOS] : Font Awesome 5 PRO - Light icon always displayed as solid

### ISSUE THREAD

**Issue by kefahB** [NathanWalker/nativescript-fonticon#22]
Hi,

On `Android` work as expected.

On `IOS`all `Light`icon are dispalyed as `solid`

`RESULT` : 

<img width="544" alt="capture d ecran 2018-12-15 a 14 47 35" src="https://user-images.githubusercontent.com/18148534/50043667-bd173100-0078-11e9-84b6-c011d98a6140.png">

Css file located in `app/fontawesome.css`

In `app.ts`: 

```ts
import {TNSFontIcon, fonticon} from 'nativescript-fonticon';

TNSFontIcon.debug = false;
TNSFontIcon.paths = {
  'fa': 'fontawesome.css'
};
TNSFontIcon.loadCss();
```

In `app/fonts` : 

<img width="203" alt="capture d ecran 2018-12-15 a 14 39 55" src="https://user-images.githubusercontent.com/18148534/50043597-6826eb00-0077-11e9-9798-dabd69ba5e09.png">

In `app/_app-common.scss` : 

```css
@font-face {
  font-family: 'Font Awesome 5 Pro';
  font-style: normal;
  font-weight: 300;
  src: url("~/fonts/fa-light-300.ttf") format("truetype")}

.fa {
  font-family: Font Awesome 5 Pro, fa-light-300;
  font-weight: 300;
}

@font-face {
  font-family: 'Font Awesome 5 Pro';
  font-style: normal;
  font-weight: 300;
  src: url("~/fonts/fa-solid-900.ttf") format("truetype")}

.fas {
  font-family: Font Awesome 5 Pro, fa-solid-900;
  font-weight: 900;
}

@font-face {
  font-family: 'Font Awesome 5 Pro';
  font-style: normal;
  font-weight: 400;
  src: url("~/fonts/fa-regular-400.ttf") format("truetype")}

.far {
  font-family: Font Awesome 5 Pro, fa-regular-400;
}
``` 

Thank you :-)

**Comment by markosole** [comment]
Hi @kefahB it's been a long time since you reported this. Just wondering did you make it work eventually? I am having problem with Font 5 Pro, where all icons are displayed as squares on iOS, but Android works fine. I am using JS of NS.

**Comment by kefahB** [comment]
Hi @markosole, Yes I did .. you should add the css `font-weight` for each one to mak it work on IOS : 

```css
.fa {
  font-family: Font Awesome 5 Pro, fa-light-300;
  font-weight: 300;
}
.fas {
  font-family: Font Awesome 5 Pro, fa-solid-900;
  font-weight: 900;
}
.fab {
  font-family: Font Awesome 5 Pro, fa-brands-400;
  font-weight: 400;
}
.far {
  font-family: Font Awesome 5 Pro, fa-regular-400;
  font-weight: 400;
}
.fad {
  font-family: Font Awesome 5 Pro, fa-dutone-900;
  font-weight: 900;
}
```
